groups:
  - name: devs # name of the group
    internal_reviewers: 6 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - simhani1
      - MustSave
      - JiheunSeo
      - LEEJW1953
      - jijongkwon
      - avatrue
      - KimYeonWook511
